--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CIRCLE
--------------------------------------------------------

  CREATE TABLE "HR"."CIRCLE" 
   (	"CIRCLE_CUS_ID" NUMBER(12,0), 
	"CIRCLE_NO" NUMBER(3,0), 
	"CIRCLE_NAME" VARCHAR2(40 BYTE), 
	"DIVISION_NAME" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.CIRCLE
SET DEFINE OFF;
Insert into HR.CIRCLE (CIRCLE_CUS_ID,CIRCLE_NO,CIRCLE_NAME,DIVISION_NAME) values (5,105,'saidapet','kk nagar');
Insert into HR.CIRCLE (CIRCLE_CUS_ID,CIRCLE_NO,CIRCLE_NAME,DIVISION_NAME) values (6,106,'reyapet','qwer nagar');
Insert into HR.CIRCLE (CIRCLE_CUS_ID,CIRCLE_NO,CIRCLE_NAME,DIVISION_NAME) values (7,107,'sdews','fjdcj');
Insert into HR.CIRCLE (CIRCLE_CUS_ID,CIRCLE_NO,CIRCLE_NAME,DIVISION_NAME) values (1,100,'chetpet','kk nagar');
Insert into HR.CIRCLE (CIRCLE_CUS_ID,CIRCLE_NO,CIRCLE_NAME,DIVISION_NAME) values (2,101,'charpet','pp nagar');
Insert into HR.CIRCLE (CIRCLE_CUS_ID,CIRCLE_NO,CIRCLE_NAME,DIVISION_NAME) values (3,103,'chrompet','mm nagar');
Insert into HR.CIRCLE (CIRCLE_CUS_ID,CIRCLE_NO,CIRCLE_NAME,DIVISION_NAME) values (4,104,'chrompet','mt nagar');
--------------------------------------------------------
--  DDL for Index SYS_C004693
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004693" ON "HR"."CIRCLE" ("CIRCLE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CIRCLE
--------------------------------------------------------

  ALTER TABLE "HR"."CIRCLE" MODIFY ("CIRCLE_CUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CIRCLE" MODIFY ("CIRCLE_NO" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CIRCLE" MODIFY ("CIRCLE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CIRCLE" MODIFY ("DIVISION_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CIRCLE" ADD UNIQUE ("CIRCLE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
