--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONSUMER
--------------------------------------------------------

  CREATE TABLE "HR"."CONSUMER" 
   (	"CUS_ID" NUMBER(12,0), 
	"CUS_NAME" VARCHAR2(100 BYTE), 
	"CUS_AGE" NUMBER(2,0), 
	"CUS_GENDER" VARCHAR2(10 BYTE), 
	"CUS_EMAIL" VARCHAR2(40 BYTE), 
	"CUS_ADDRESS" VARCHAR2(200 BYTE), 
	"CUS_PINCODE" NUMBER(6,0), 
	"CUS_PHONENUMBER" NUMBER(12,0), 
	"CUS_AADHARNUMBER" NUMBER(12,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.CONSUMER
SET DEFINE OFF;
Insert into HR.CONSUMER (CUS_ID,CUS_NAME,CUS_AGE,CUS_GENDER,CUS_EMAIL,CUS_ADDRESS,CUS_PINCODE,CUS_PHONENUMBER,CUS_AADHARNUMBER) values (5,'arya',36,'male','arya@gmail.com','566,pot nagar',564434,2345675434,22334455667);
Insert into HR.CONSUMER (CUS_ID,CUS_NAME,CUS_AGE,CUS_GENDER,CUS_EMAIL,CUS_ADDRESS,CUS_PINCODE,CUS_PHONENUMBER,CUS_AADHARNUMBER) values (1,'suriya',23,'male','sur@gmail.com','123,plot red',1234,123345,543211);
Insert into HR.CONSUMER (CUS_ID,CUS_NAME,CUS_AGE,CUS_GENDER,CUS_EMAIL,CUS_ADDRESS,CUS_PINCODE,CUS_PHONENUMBER,CUS_AADHARNUMBER) values (2,'vijay',25,'male','vij@gmail.com','456,plot red',1234,122245,6666);
Insert into HR.CONSUMER (CUS_ID,CUS_NAME,CUS_AGE,CUS_GENDER,CUS_EMAIL,CUS_ADDRESS,CUS_PINCODE,CUS_PHONENUMBER,CUS_AADHARNUMBER) values (3,'jai',21,'male','jai@gmail.com','789,plot red',1234,111145,77777);
Insert into HR.CONSUMER (CUS_ID,CUS_NAME,CUS_AGE,CUS_GENDER,CUS_EMAIL,CUS_ADDRESS,CUS_PINCODE,CUS_PHONENUMBER,CUS_AADHARNUMBER) values (4,'anjali',25,'female','anj@gmail.com','no:33,poiyas garden',625,9984335,76543);
Insert into HR.CONSUMER (CUS_ID,CUS_NAME,CUS_AGE,CUS_GENDER,CUS_EMAIL,CUS_ADDRESS,CUS_PINCODE,CUS_PHONENUMBER,CUS_AADHARNUMBER) values (6,'anand',24,'male','anand@gmail.com','plot.no:34,polar road, chennai',654453,8489835539,23443456798);
Insert into HR.CONSUMER (CUS_ID,CUS_NAME,CUS_AGE,CUS_GENDER,CUS_EMAIL,CUS_ADDRESS,CUS_PINCODE,CUS_PHONENUMBER,CUS_AADHARNUMBER) values (7,'somu',23,'male','farooq@gmail.com','234,jolterpet',627009,9876543210,987543223);
--------------------------------------------------------
--  DDL for Index SYS_C004703
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004703" ON "HR"."CONSUMER" ("CUS_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004704
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004704" ON "HR"."CONSUMER" ("CUS_PHONENUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004705
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004705" ON "HR"."CONSUMER" ("CUS_AADHARNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONSUMER
--------------------------------------------------------

  ALTER TABLE "HR"."CONSUMER" ADD CONSTRAINT "CONSUMER_GENDER" CHECK (cus_gender in('male','female','others')) ENABLE;
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_AGE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_PINCODE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_PHONENUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" MODIFY ("CUS_AADHARNUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."CONSUMER" ADD UNIQUE ("CUS_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."CONSUMER" ADD UNIQUE ("CUS_PHONENUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."CONSUMER" ADD UNIQUE ("CUS_AADHARNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
