--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOGINDETAILS
--------------------------------------------------------

  CREATE TABLE "HR"."LOGINDETAILS" 
   (	"CUSTOMER_ID" NUMBER(10,0), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.LOGINDETAILS
SET DEFINE OFF;
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (12345,'admin');
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (1,'aravind');
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (2,'anbu');
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (3,'siva');
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (4,'ajay');
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (5,'bala');
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (6,'naveen');
Insert into HR.LOGINDETAILS (CUSTOMER_ID,PASSWORD) values (7,'mahe');
--------------------------------------------------------
--  DDL for Index SYS_C004714
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004714" ON "HR"."LOGINDETAILS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LOGINDETAILS
--------------------------------------------------------

  ALTER TABLE "HR"."LOGINDETAILS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."LOGINDETAILS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."LOGINDETAILS" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
