--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table METER
--------------------------------------------------------

  CREATE TABLE "HR"."METER" 
   (	"METER_CUS_ID_SEQ" NUMBER(12,0), 
	"MET_NO" NUMBER(6,0), 
	"MET_UNIT" NUMBER(6,0), 
	"MET_MONTH" VARCHAR2(15 BYTE), 
	"MET_AMOUNT" NUMBER(6,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.METER
SET DEFINE OFF;
Insert into HR.METER (METER_CUS_ID_SEQ,MET_NO,MET_UNIT,MET_MONTH,MET_AMOUNT) values (6,106,260,'July',440);
Insert into HR.METER (METER_CUS_ID_SEQ,MET_NO,MET_UNIT,MET_MONTH,MET_AMOUNT) values (7,108,1232,'June',24324);
Insert into HR.METER (METER_CUS_ID_SEQ,MET_NO,MET_UNIT,MET_MONTH,MET_AMOUNT) values (1,100,230,'may',277);
Insert into HR.METER (METER_CUS_ID_SEQ,MET_NO,MET_UNIT,MET_MONTH,MET_AMOUNT) values (2,101,330,'may',440);
Insert into HR.METER (METER_CUS_ID_SEQ,MET_NO,MET_UNIT,MET_MONTH,MET_AMOUNT) values (3,102,430,'may',610);
Insert into HR.METER (METER_CUS_ID_SEQ,MET_NO,MET_UNIT,MET_MONTH,MET_AMOUNT) values (4,103,321,'may',490);
Insert into HR.METER (METER_CUS_ID_SEQ,MET_NO,MET_UNIT,MET_MONTH,MET_AMOUNT) values (5,105,201,'September',450);
--------------------------------------------------------
--  DDL for Index SYS_C004711
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004711" ON "HR"."METER" ("MET_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table METER
--------------------------------------------------------

  ALTER TABLE "HR"."METER" MODIFY ("METER_CUS_ID_SEQ" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."METER" MODIFY ("MET_NO" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."METER" MODIFY ("MET_UNIT" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."METER" MODIFY ("MET_MONTH" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."METER" MODIFY ("MET_AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."METER" ADD PRIMARY KEY ("MET_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
