--------------------------------------------------------
--  File created - Friday-May-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRN_CARDS
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_CARDS" 
   (	"CARD_NUMBER" NUMBER(20,0), 
	"CUSTOMER_NAME" VARCHAR2(50 BYTE), 
	"CARD_CVV" NUMBER(5,0), 
	"EXP_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRN_ADMIN
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_ADMIN" 
   (	"ADMIN_NAME" VARCHAR2(50 BYTE), 
	"ADMIN_ID" NUMBER(10,0), 
	"ADMIN_USERNAME" VARCHAR2(30 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(30 BYTE), 
	"BANK_AC_NUMBER" NUMBER(10,2) DEFAULT 0
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRN_CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_CUSTOMERS" 
   (	"ACCOUNT_NUMBER" NUMBER(15,0), 
	"CUSTOMER_NAME" VARCHAR2(50 BYTE), 
	"CUSTOMER_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"PHONE_NUMBER" NUMBER(12,0), 
	"FATHERS_NAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(7 BYTE), 
	"BALANCE" NUMBER(12,2) DEFAULT 0, 
	"USERNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"DOB" DATE, 
	"PERMANENT_ADDRESS" VARCHAR2(250 BYTE), 
	"PERMANENT_CITY" VARCHAR2(25 BYTE), 
	"CURRENT_ADDRESS" VARCHAR2(250 BYTE), 
	"CURRENT_CITY" VARCHAR2(25 BYTE), 
	"STATE" VARCHAR2(25 BYTE), 
	"IFSC_CODE" VARCHAR2(10 BYTE), 
	"FLAG" NUMBER(2,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"MMID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRN_IFSC
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_IFSC" 
   (	"CURRENT_CITY" VARCHAR2(25 BYTE), 
	"IFSC_CODE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRN_PAYEE
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_PAYEE" 
   (	"ACCOUNT_NUMBER" NUMBER(15,0), 
	"PAYEE_NAME" VARCHAR2(50 BYTE), 
	"TRANSACTION_ID" NUMBER(10,0), 
	"IFSC_CODE" VARCHAR2(10 BYTE), 
	"MMID" NUMBER(10,0), 
	"REMARKS" VARCHAR2(100 BYTE), 
	"BALANCE" NUMBER(12,2), 
	"TRANSACTION_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRN_TRNSC_LIST
--------------------------------------------------------

  CREATE TABLE "HR"."TRN_TRNSC_LIST" 
   (	"CUSTOMER_ID" NUMBER(10,0), 
	"TRANSACTION_ID" NUMBER(10,0), 
	"CURRENT_BALANCE" NUMBER(10,2) DEFAULT 0, 
	"AMOUNT" NUMBER(10,2) DEFAULT 0, 
	"BENF_AC_NUMBER" NUMBER(15,0), 
	"TRANSACTION_DATE" TIMESTAMP (6), 
	"MMID" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.TRN_CARDS
SET DEFINE OFF;
REM INSERTING into HR.TRN_ADMIN
SET DEFINE OFF;
REM INSERTING into HR.TRN_CUSTOMERS
SET DEFINE OFF;
Insert into HR.TRN_CUSTOMERS (ACCOUNT_NUMBER,CUSTOMER_NAME,CUSTOMER_ID,EMAIL,PHONE_NUMBER,FATHERS_NAME,GENDER,BALANCE,USERNAME,PASSWORD,DOB,PERMANENT_ADDRESS,PERMANENT_CITY,CURRENT_ADDRESS,CURRENT_CITY,STATE,IFSC_CODE,FLAG,CREATED_DATE,MODIFIED_DATE,MMID) values (620410100000,'Athiselvam',5000,'athitek@rediffmail.com',9042401691,'Nainar','Male',23824,'its773','pass123',to_date('11-05-97','DD-MM-RR'),'shanmugam street','shencottai','shanmugam street','shencottai','Tamil nadu','ATEK000138',1,to_timestamp('21-05-19 06:14:19.555000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('21-05-19 06:14:19.555000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),8807651);
Insert into HR.TRN_CUSTOMERS (ACCOUNT_NUMBER,CUSTOMER_NAME,CUSTOMER_ID,EMAIL,PHONE_NUMBER,FATHERS_NAME,GENDER,BALANCE,USERNAME,PASSWORD,DOB,PERMANENT_ADDRESS,PERMANENT_CITY,CURRENT_ADDRESS,CURRENT_CITY,STATE,IFSC_CODE,FLAG,CREATED_DATE,MODIFIED_DATE,MMID) values (620410100001,'Karpagaganesh',5001,'karpagaganesh@yahoo.com',8778132253,'Nallappan','Male',996668,'karpagaganesh nallappan','password',to_date('12-10-98','DD-MM-RR'),'villapuram housing board','madurai','villapuram housing board','madurai','Tamil nadu','ATEK000134',1,to_timestamp('21-05-19 06:40:15.063000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),to_timestamp('21-05-19 06:40:15.063000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),null);
REM INSERTING into HR.TRN_IFSC
SET DEFINE OFF;
REM INSERTING into HR.TRN_PAYEE
SET DEFINE OFF;
REM INSERTING into HR.TRN_TRNSC_LIST
SET DEFINE OFF;
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1428,996668,440,620410100000,to_timestamp('23-05-19 02:30:56.630000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1420,1000000,111,620410100000,to_timestamp('22-05-19 09:34:30.789000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1421,1000000,111,620410100000,to_timestamp('22-05-19 10:17:17.466000000 AM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1424,998428,450,620410100000,to_timestamp('23-05-19 01:51:45.932000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1425,997988,440,620410100000,to_timestamp('23-05-19 02:10:21.774000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1426,997548,440,620410100000,to_timestamp('23-05-19 02:13:12.245000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1422,999001,999,620410100000,to_timestamp('22-05-19 02:10:47.401000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1423,998878,123,620410100000,to_timestamp('22-05-19 02:12:39.127000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),0);
Insert into HR.TRN_TRNSC_LIST (CUSTOMER_ID,TRANSACTION_ID,CURRENT_BALANCE,AMOUNT,BENF_AC_NUMBER,TRANSACTION_DATE,MMID) values (5001,1427,997108,440,620410100000,to_timestamp('23-05-19 02:23:08.186000000 PM','DD-MM-RR HH12:MI:SSXFF AM'),0);
--------------------------------------------------------
--  DDL for Index SYS_C004639
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004639" ON "HR"."TRN_ADMIN" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004640
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004640" ON "HR"."TRN_ADMIN" ("ADMIN_USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRN_CUSTOMER_ACNUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TRN_CUSTOMER_ACNUM_PK" ON "HR"."TRN_CUSTOMERS" ("ACCOUNT_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004621
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004621" ON "HR"."TRN_CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004622
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004622" ON "HR"."TRN_CUSTOMERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004623
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004623" ON "HR"."TRN_CUSTOMERS" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004624
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004624" ON "HR"."TRN_CUSTOMERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C004630
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C004630" ON "HR"."TRN_IFSC" ("CURRENT_CITY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TRN_CARDS
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_CARDS" MODIFY ("CARD_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CARDS" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CARDS" MODIFY ("CARD_CVV" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CARDS" MODIFY ("EXP_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRN_ADMIN
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_ADMIN" MODIFY ("ADMIN_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_ADMIN" MODIFY ("ADMIN_USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_ADMIN" MODIFY ("ADMIN_PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_ADMIN" ADD UNIQUE ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_ADMIN" ADD UNIQUE ("ADMIN_USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRN_CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CUSTOMER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("FATHERS_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("GENDER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("DOB" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PERMANENT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("PERMANENT_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CURRENT_ADDRESS" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CURRENT_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("STATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("IFSC_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" MODIFY ("MODIFIED_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("PHONE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."TRN_CUSTOMERS" ADD CONSTRAINT "TRN_CUSTOMER_ACNUM_PK" PRIMARY KEY ("ACCOUNT_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRN_IFSC
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_IFSC" MODIFY ("CURRENT_CITY" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_IFSC" MODIFY ("IFSC_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_IFSC" ADD UNIQUE ("CURRENT_CITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRN_PAYEE
--------------------------------------------------------

  ALTER TABLE "HR"."TRN_PAYEE" MODIFY ("ACCOUNT_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PAYEE" MODIFY ("PAYEE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PAYEE" MODIFY ("IFSC_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PAYEE" MODIFY ("MMID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."TRN_PAYEE" MODIFY ("TRANSACTION_DATE" NOT NULL ENABLE);
